apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "seafile.fullname" . }}-storage-classes
data:
  seafile_storage_classes.json: |-
    [
      {
        "storage_id": "S3",
        "name": "S3",
        "is_default": true,
        "commits": {
          "backend": "s3",
          {{- if .Values.minio.enabled }}
          "host": {{ printf "%s-minio:9000" .Release.Name | quote }},
          {{- else}}
          "host": "{{ .Values.seafileConfig.s3.host }}:{{ .Values.seafileConfig.s3.port }}",
          {{- end }}
          "use_https": {{ .Values.seafileConfig.s3.use_https | quote }},
          "bucket": {{ .Values.seafileConfig.s3.bucketNameCommits | quote }},
          "key_id": {{ .Values.seafileConfig.s3.apiKey | quote }},
          "key": {{ .Values.seafileConfig.s3.apiKeyPass | quote }},
          "path_style_request": {{ .Values.seafileConfig.s3.path_style_request }}
        },
        "fs": {
          "backend": "s3",
          {{- if .Values.minio.enabled }}
          "host": {{ printf "%s-minio:9000" .Release.Name | quote }},
          {{- else}}
          "host": "{{ .Values.seafileConfig.s3.host }}:{{ .Values.seafileConfig.s3.port }}",
          {{- end }}
          "use_https": {{ .Values.seafileConfig.s3.use_https | quote }},
          "bucket": {{ .Values.seafileConfig.s3.bucketNameFs | quote }},
          "key_id": {{ .Values.seafileConfig.s3.apiKey | quote }},
          "key": {{ .Values.seafileConfig.s3.apiKeyPass | quote }},
          "path_style_request": {{ .Values.seafileConfig.s3.path_style_request }}
        },
        "blocks": {
          "backend": "s3",
          {{- if .Values.minio.enabled }}
          "host": {{ printf "%s-minio:9000" .Release.Name | quote }},
          {{- else}}
          "host": "{{ .Values.seafileConfig.s3.host }}:{{ .Values.seafileConfig.s3.port }}",
          {{- end }}
          "use_https": {{ .Values.seafileConfig.s3.use_https | quote }},
          "bucket": {{ .Values.seafileConfig.s3.bucketNameBlocks | quote }},
          "key_id": {{ .Values.seafileConfig.s3.apiKey | quote }},
          "key": {{ .Values.seafileConfig.s3.apiKeyPass | quote }},
          "path_style_request": {{ .Values.seafileConfig.s3.path_style_request }}
        }
      }
    ]
